name: Execução de testes funcionais

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9,11,16 * * 1,2,3,4,5'

jobs:
  testes-funcionais: ubuntu-latest

    steps:
    
